version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: github-actions
    schedule:
      interval: daily
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily